
export const SUCCESS = "SUCCESS"
export const FAILURE = "FAILURE"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"
export const LOGOUT = "LOGOUT";
export const FETCH_INGREDIENTS = "FETCH_SUCCESS";
export const ADD_PROFILE = "ADD_PROFILE"
export const REMOVE_PROFILE = "REMOVE_PROFILE"

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";