

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"
export const LOGOUT = "LOGOUT";
export const FETCH_INGREDIENTS = "FETCH_SUCCESS";
export const FETCH_INGREDIENT = "FETCH_INGREDIENT";
export const DELETE_INGREDIENT = "DELETE_INGREDIENT"
export const CREATE_INGREDIENT = "CREATE_INGREDIENT";
export const UPDATE_INGREDIENT = "UPDATE_INGREDIENT";
export const INGREDIENT_TYPES = "INGREDIENT_TYPES";
export const ADD_PROFILE = "ADD_PROFILE"
export const REMOVE_PROFILE = "REMOVE_PROFILE"
export const SUCCESS = "SUCCESS"
export const ERROR = "ERROR"
export const MESSAGE = "MESSAGE"
export const FETCH_NOTIFICATIONS = "FETCH_NOTIFCIATIONS"
export const FETCH_LOGS = "FETCH_LOGS"